services:
  mongo-auth:
    image: mongo:8.0
    container_name: mongo-auth
    restart: always
    volumes:
      - mongo-auth-data:/data/db/reward
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12qwaszx
      MONGO_INITDB_DATABASE: reward_auth
    ports:
      - "27017:27017"

  mongo-event:
    image: mongo:8.0
    container_name: mongo-event
    restart: always
    volumes:
      - mongo-event-data:/data/db/reward
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12qwaszx
      MONGO_INITDB_DATABASE: reward_event
    ports:
      - "27018:27017"

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: reward-platform-gateway
    restart: on-failure
    environment:
      AUTH_SERVICE_HOST: auth
      AUTH_SERVICE_PORT: 3001
      EVENT_SERVICE_HOST: event
      EVENT_SERVICE_PORT: 3002
      JWT_SECRET_KEY: JWT_SECRET_KEY
    depends_on:
      - auth
      - event
    ports:
      - "3000:3000"

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: reward-auth
    restart: on-failure
    environment:
      AUTH_MONGO_URI: mongodb://root:12qwaszx@mongo-auth:27017/reward_auth?authSource=admin
      JWT_SECRET_KEY: JWT_SECRET_KEY
      JWT_EXPIRES_IN: 10m
      JWT_REFRESH_EXPIRES_IN: 1d
    depends_on:
      - mongo-auth
    ports:
      - "3001:3001"

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    container_name: reward-event
    restart: on-failure
    environment:
      AUTH_MONGO_URI: mongodb://root:12qwaszx@mongo-auth:27017/reward_event?authSource=admin
      JWT_SECRET_KEY: JWT_SECRET_KEY
      JWT_EXPIRES_IN: 10m
      JWT_REFRESH_EXPIRES_IN: 1d
    depends_on:
      - mongo-event
    ports:
      - "3002:3002"

volumes:
  mongo-auth-data:
  mongo-event-data:

networks:
  reward:
    driver: bridge
